### PR TITLE
Add support for SOAP 1.1

### PR DESCRIPTION
**Pull request by shackpank**
I get the feeling we'll be needing this soon. _(ask me if you need to know why, doesn't need to go on public repo)_

SOAP 1.1 and 1.2 servers expect different content-type headers to be sent along with requests, this adds a CLI option `--soap-version` to allow you to choose which when the library is generated. The default is 1.2, ie how wsdl2.js currently behaves.

The main change is introducing `minimist` for CLI option parsing to accept the new `--soap-version` argument. While I was there I put in a bit more validation of the existing CLI options so it outputs a help message rather than crashes out failing to make a directory or read a file if you're using it wrong.

Included a version bump, readme update, and adds a `CHANGELOG` because that's a nice thing to have.

14qj3mv

### CODE REVIEW

**Comment by rahulpatel** [comment]
Looks good to me! +1

**Comment by stuartstobie** [comment]
Checked this out and it looks good +1

**Comment by hx-markterry** [comment]
I'm going to be that man and suggest that this should have a test. The package.json does state it produces a high quality library.

**Comment by rahulpatel** [comment]
@hx-markterry I've added a test which generates a test library and checks for the key folders and files.

**Comment by hx-markterry** [comment]
looks good +1

**Comment by hxoliverrumbelow** [comment]
+1

**Comment by billinghamj** [comment]
+1

**Comment by billinghamj** [comment]
Could this be pushed to npm please?

**Comment by shackpank** [comment]
Hi @billinghamj

We've discovered a post-merge bug in our own testing, #11 which we'll merge ahead of a new npm release, hopefully today!

**Comment by rahulpatel** [comment]
Hi @billinghamj,

We've published `v0.2.0` to npm with the changes in the pull request!

**Comment by billinghamj** [comment]
Much appreciated

**Pull request merged**
